#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Render selected PDF pages into V6 evidence snapshots.

Safety:
- dry-run by default;
- writes only with --apply;
- never copies the source PDF;
- output metadata marks items as pending-verification unless the caller explicitly sets confidence/status;
- fails honestly if PyMuPDF is unavailable in apply mode.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Iterable


@dataclass
class SnapshotPlan:
    evidence_id: str
    course: str
    source_type: str
    source_path: str
    page: int
    output_path: str
    metadata_path: str
    confidence: str
    status: str
    extractor: str


def slugify(text: str) -> str:
    cleaned = re.sub(r"[^0-9A-Za-z\u4e00-\u9fff]+", "-", text).strip("-")
    return cleaned or "course"


def parse_pages(spec: str) -> list[int]:
    pages: set[int] = set()
    for part in spec.split(','):
        part = part.strip()
        if not part:
            continue
        if '-' in part:
            start_s, end_s = part.split('-', 1)
            start, end = int(start_s), int(end_s)
            if start < 1 or end < start:
                raise ValueError(f"invalid page range: {part}")
            pages.update(range(start, end + 1))
        else:
            page = int(part)
            if page < 1:
                raise ValueError(f"invalid page: {part}")
            pages.add(page)
    return sorted(pages)


def build_plan(pdf: Path, course: str, pages: Iterable[int], output_dir: Path, confidence: str = "B", status: str = "pending-verification") -> list[SnapshotPlan]:
    slug = slugify(course)
    digest = hashlib.sha1(str(pdf).encode('utf-8', errors='ignore')).hexdigest()[:8]
    plans: list[SnapshotPlan] = []
    for page in pages:
        evidence_id = f"{slug}-pdf-p{page:03d}-{digest}"
        image_path = output_dir / f"{evidence_id}.png"
        metadata_path = output_dir / f"{evidence_id}.json"
        plans.append(SnapshotPlan(
            evidence_id=evidence_id,
            course=course,
            source_type="pdf",
            source_path=str(pdf),
            page=page,
            output_path=str(image_path),
            metadata_path=str(metadata_path),
            confidence=confidence,
            status=status,
            extractor="scripts/v6/pdf_page_snapshot.py",
        ))
    return plans


def render_with_pymupdf(pdf: Path, plan: SnapshotPlan, dpi: int) -> None:
    try:
        import fitz  # type: ignore
    except Exception as exc:  # pragma: no cover - depends on optional env
        raise RuntimeError("PyMuPDF/fitz is required for --apply PDF rendering") from exc
    doc = fitz.open(str(pdf))
    try:
        if plan.page < 1 or plan.page > len(doc):
            raise ValueError(f"page {plan.page} out of range for {pdf} ({len(doc)} pages)")
        page = doc[plan.page - 1]
        pix = page.get_pixmap(dpi=dpi)
        Path(plan.output_path).parent.mkdir(parents=True, exist_ok=True)
        pix.save(plan.output_path)
    finally:
        doc.close()


def write_metadata(plan: SnapshotPlan) -> None:
    meta = asdict(plan)
    meta["created"] = date.today().isoformat()
    meta["source_ref"] = {"page": plan.page, "timestamp": None, "frame_index": None}
    meta["notes"] = ["Generated by V6 PDF snapshot tool; verify course relevance before promoting confidence to A."]
    Path(plan.metadata_path).write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding='utf-8')


def execute(pdf: Path, course: str, pages: str, output_dir: Path, apply: bool = False, dpi: int = 160) -> dict:
    if not pdf.exists():
        raise FileNotFoundError(str(pdf))
    page_nums = parse_pages(pages)
    plans = build_plan(pdf, course, page_nums, output_dir)
    result = {"apply": apply, "pdf": str(pdf), "course": course, "pages": page_nums, "plans": [asdict(p) for p in plans]}
    if apply:
        output_dir.mkdir(parents=True, exist_ok=True)
        for plan in plans:
            render_with_pymupdf(pdf, plan, dpi=dpi)
            write_metadata(plan)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('pdf', type=Path)
    parser.add_argument('--course', required=True)
    parser.add_argument('--pages', required=True, help='1,2,5-7')
    parser.add_argument('--output-dir', type=Path, required=True)
    parser.add_argument('--dpi', type=int, default=160)
    parser.add_argument('--apply', action='store_true')
    args = parser.parse_args()
    print(json.dumps(execute(args.pdf, args.course, args.pages, args.output_dir, apply=args.apply, dpi=args.dpi), ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
